옷생성 api 추가
KWEBofficial/stylevillage-server pull request #10
Opened 2024-01-05 16:26 UTC by Dcaffein

createClothes 추가했습니다

2024-01-06 01:28 UTC, readygetset requested changes

2024-01-06 01:28 UTC, readygetset commented on src/controller/clothes/controller.ts
> +
로그인 여부 확인해야 할 거 같아요 토큰 없어도 실행됩니다 ㅠㅠ 그 외에는 실행 잘 되네요 수고 많으셨습니다!

2024-01-06 06:06 UTC, readygetset approved these changes
LGTM!

2024-01-06 06:39 UTC, foura1201 requested changes

2024-01-06 06:39 UTC, foura1201 commented on src/controller/clothes/controller.ts
> +      res.status(401).json({ error: '로그인이 필요한 기능입니다.' });
`throw new UnauthorizedError('로그인이 필요한 기능입니다.')`로 수정하면 더 좋을 것 같습니당

2024-01-06 06:39 UTC, foura1201 commented on src/controller/clothes/controller.ts
> +    }
enum 유효성 검사는 자주 사용될 것 같아서 util 폴더에 따로 함수들을 만들어두고 사용하는 것이 좋을 것 같습니다! 일단은 이렇게 두고 나중에 따로 작업할당해드릴게용

2024-01-06 06:39 UTC, foura1201 commented on src/type/clothes/createClothes.res.ts
> +export default interface CreaetClothesRes {
CreateClothesRes로 수정해주세요!

2024-01-06 06:39 UTC, foura1201 commented on src/entity/clothes.entity.ts
> +  is_open!: boolean;
이부분 isOpen으로 수정해주세요!

2024-01-06 06:39 UTC, foura1201 commented on src/controller/clothes/router.ts
> +// 진짜 말이 안되는건데, 위의 주석을 지우면 clothes/controller.ts는 모듈이 아니라는 에러가 뜹니다..
이 부분 저한테는 에러가 발생하지 않아서 주석 지운 다음 vscode 껐다켜보고도 에러가 발생한다면 말씀해주세요!

2024-01-06 06:39 UTC, foura1201 commented on src/controller/clothes/controller.ts
> +    }
Todo로 enum 유효성 검사 기능 분리라고 적어주시면 좋을 것 같습니당!

2024-01-06 09:13 UTC, Dcaffein commented on src/controller/clothes/controller.ts
> +    }
issue 생성해둘까요?

2024-01-06 23:24 UTC, foura1201 commented on src/controller/clothes/router.ts
> +// 진짜 말이 안되는건데, 위의 주석을 지우면 clothes/controller.ts는 모듈이 아니라는 에러가 뜹니다..
저 혹시 이 부분은 해결이 안된건가요?

2024-01-07 03:52 UTC, foura1201 commented on src/controller/clothes/controller.ts
> +    }
넵넵!

2024-01-07 04:18 UTC, Dcaffein commented on src/controller/clothes/router.ts
> +// 진짜 말이 안되는건데, 위의 주석을 지우면 clothes/controller.ts는 모듈이 아니라는 에러가 뜹니다..
아 해결되었습니다. 이 부분 저장 안된상태에서 commit이 올라간 것 같네요

2024-01-07 09:09 UTC, merged