feat: get-clothes api 추가
KWEBofficial/stylevillage-server pull request #15
Opened 2024-01-06 07:27 UTC by SJBae1

옷 상세 가져오기 API 추가하였습니다.
getClothes/controller.ts 16-17행에서 Clothes entity의 id가 ?로 설정되어있어 undefined 값때문에 compatible하지 않아 할당할 수 없다고 하여 clothes.entity.ts를 id? = number; -> id! = number;로 변경하였습니다.

파일을 clothes에 병합해야할 것 같은데 우선은 getClothes로 모두 분리해두었습니다.

2024-01-06 10:19 UTC, Dcaffein commented on src/type/getClothes/getClothes.res.ts
> +  id: number;
Response에서 id를 nullable로 설정했더니 말씀하신대로 entity에서 id? -> id! 로 바꾸는건 피해갈 수 있더라고요.
response에서 id가 null이 나오는 경우가 있으면 안되긴 하는데, 그건 controller에서 막아줄 수 있지 않을까해서요.

2024-01-06 11:12 UTC, Dcaffein approved these changes

2024-01-07 04:02 UTC, foura1201 commented on src/controller/getClothes/controller.ts
> +    if (!clothesId) throw new BadRequestError('해당 의류를 찾을 수 없습니다.');
이 부분은 해당 의류를 찾을 수 없다는 에러 메세지 보다는 clothesId가 필요하다는 메세지면 더 좋을 것 같습니당

2024-01-07 04:03 UTC, foura1201 commented
controller에 폴더명을 getClothes가 아닌 clothes로 변경해주세용

2024-01-07 11:05 UTC, foura1201 commented
지금 user entity가 잘못 수정된 것 같은데 혹시 원래대로 돌려주실 수 있을까요?

2024-01-07 11:15 UTC, foura1201 requested changes

2024-01-07 11:15 UTC, foura1201 commented on src/controller/clothes/router.ts
> +getClothesRouter.get('/:clothesId', getClothes);
getClothes router는 삭제하고 clothesRouter에 getClothes controller 연결해주세요!

2024-01-07 11:15 UTC, foura1201 commented on src/controller/router.ts
> +router.use('/clothes', getClothesRouter);
마찬가지로 `router.use('/clothes', getClothesRouter);`부분은 삭제해주세용

2024-01-07 11:15 UTC, foura1201 commented on src/entity/user.entity.ts
> +export default class User {
user entity가 수정되면 안됩니다! develop에 있는 내용대로 다시 변경 부탁드립니다

2024-01-07 11:15 UTC, foura1201 commented on src/repository/clothes.repository.ts
> +});
GetClothesRepository는 삭제하고 ClothesRepository 내에서 메서드 작성해주세용

2024-01-07 11:15 UTC, foura1201 commented on src/service/getClothes.service.ts
> +export default class GetClothesService {
서비스 이름도 ClothesService로 변경해주세용

2024-01-07 11:22 UTC, SJBae1 commented
조금전에 확인해서 전부 변경중입니다!

2024-01-07 12:24 UTC, foura1201 requested changes

2024-01-07 12:24 UTC, foura1201 commented on src/repository/clothes.repository.ts
> +const GetClothesRepository = AppDataSource.getRepository(Clothes).extend({
이부분 수정이 안된 것 같습니다! ClothesRepostiory 내에서 메서드 작성하고 GetClothesRepository는 삭제해주세요

2024-01-07 12:35 UTC, foura1201 requested changes

2024-01-07 12:35 UTC, foura1201 commented on src/service/clothes.service.ts
> +    if (!clothes.isOpen) throw new ForbiddenError('공개되지 않은 옷입니다.');
이 부분 자기 자신의 옷을 가져오는 경우도 생각해서 req.user에 값이 있고 해당 user가 소유자가 맞다면 옷을 가져올 수 있도록 하는 게 맞는 것 같습니당..!

2024-01-07 15:36 UTC, foura1201 approved these changes
LGTM!

2024-01-07 15:54 UTC, merged