Feature/get user without
KWEBofficial/stylevillage-server pull request #46
Opened 2024-01-13 12:47 UTC by readygetset

사용자 정보를 토큰만으로 가져올 수 있게 했습니다.

2024-01-13 13:30 UTC, foura1201 requested changes
혹시 이 api가 필요한 이유가 무엇인지 궁금합니다..!

2024-01-13 13:30 UTC, foura1201 commented on src/controller/user/controller.ts
> +      ? await UserService.getUserById(id)
query에서 받은 id만으로 유저 정보를 가져올 수 있는 로직은 없애는 게 좋을 것 같습니다. 본인 외 사용자의 정보를 쉽게 가져올 수 있는 취약점이 될 수 있을 것 같습니당

2024-01-13 13:37 UTC, foura1201 commented
혹시 사용자 인증 상태 관리를 위한 것이라면 로컬 스토리지를 이용하여 해결할 수도 있을 것 같습니다!
https://wikidocs.net/197733

2024-01-13 13:45 UTC, readygetset commented on src/controller/user/controller.ts
> +      ? await UserService.getUserById(id)
사용자 이름을 가져와서 쓰는 일이 많을 거 같아서요! 예를 들어서 네비게이션 바에도 ___님 이렇게 넣으려면 필요할 거 같아서 그렇습니당

2024-01-13 13:48 UTC, foura1201 commented on src/controller/user/controller.ts
> +      ? await UserService.getUserById(id)
사용자 정보가 필요할 때마다 api를 날리는 것이 불필요한 비용이 발생하는 것은 아닌가하는 생각이 조금 드는데 혹시 전역 상태 관리나 스토리지를 이용하는 등의 방법으로 해결하는 것은 어려울까요?

2024-01-14 01:42 UTC, readygetset commented on src/controller/user/controller.ts
> +      ? await UserService.getUserById(id)
아 넵 그럼 PR 닫고 그런 식으로 해보겠습니당

2024-01-14 01:42 UTC, closed without merging